cmd/commands: add PostgresSQL DB statement_cache_mode config opt
Fix error when PG DB connection pool is used:

```
ERROR: prepared statement "lrupsc_1_6" already exists (SQLSTATE 42P05)
```

https://pkg.go.dev/github.com/jackc/pgx/v4#ParseConfig